POST http://localhost:3001/api/admins/addAdmin
Content-Type: application/json

{
    "email" : "naoufal@gmail.com",
    "password" : "1111"
}

####

POST http://localhost:3001/api/admins/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "azer"
}

####

POST http://localhost:3001/api/admins/decode
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJfaWQiOiI2MWU4NjJiYmU3MGYyY2Q4YmU2ZWUyMDciLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDBpUVRpVHcvZWR5N3JYeE5ReW1NeHVJTzQycnJoVWV4M1kwQlpWOEs3eHdocGVvRVFNYlZlIiwiX192IjowfSwiaWF0IjoxNjQyNzc4MDAwfQ.1LI8NJTBTrWZNdWzlx80UhAWSkQ6aHkjxO0J2292y4I"
}

####

GET http://localhost:3001/api/places/getPlaces

####

GET http://localhost:3001/api/places/getPlaceById/61e600e0e8c5cec97d8e4671